routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Gloudemans\Shoppingcart\Facades\Cart;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});




Route::get('/', 'MainController@index')->name('index');
Route::resource('category', 'CategoryController');
Route::get('/price/{mix}/{max}', 'PriceController@show')->name('price.show');

Route::get('/products', 'ProductController@index')->name('products.index');
Route::get('/products/{id}', 'ProductController@show')->name('products.show');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/admin', 'AdminController@index')->name('admin.index');

    Route::resource('categorymanager', 'CategoryManagerController');
    Route::resource('productmanager', 'ProductManagerController');
    Route::resource('usermanager', 'UserManagerController');
    Route::resource('ordermanager', 'OrderManagerController');


    //Orders
    Route::resource('/orders', 'OrderController');

    Route::get('/thank-you', function () {
        return view('thank-you');
    })->name('thank-you');

    Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');
    Route::post('/checkout', 'CheckoutController@store')->name('checkout.store');
    //cart
    Route::get('/cart', 'CartController@index')->name('cart.index');
    Route::post('/cart', 'CartController@store')->name('cart.store');

    Route::post('/cart/empty', 'CartController@empty')->name('cart.empty');
    Route::delete('/cart/{id}', 'CartController@destroy')->name('cart.destroy');
    Route::put('/cart/{id}', 'CartController@update')->name('cart.update');


    //Profile
    Route::get('/profile', 'ProfileController@index')->name('profile.index');
    Route::get('/profile/{id}/edit', 'ProfileController@edit')->name('profile.edit');
    Route::put('/profile/{id}', 'ProfileController@update')->name('profile.update');
});

app/Http/Controllers/ProductManagerController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;

class ProductManagerController extends Controller
{
    //page admin
    //route GET /productmanager
    public function index()
    {
        //jib les derniers 5 products
        $products = Product::latest()->paginate(5);

        //afficher lview li kayna fi /resources/views/productmanager/index.blade.php 
        //osift lya m3aha les variables 'products'
        return view('productmanager.index', compact('products'));
    }

    //route GET /productmanager/create
    public function create()
    {
        //jib les titre dyal tous les categories
        $categories = Category::all();

        //afficher lview li kayna fi /resources/views/productmanager/create.blade.php 
        return view('productmanager.create', compact('categories'));
    }


    //route POST /productmanager
    public function store(Request $request)
    {
        //validation des champs
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'category_id' => 'required',
            'price' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        //9ad slug, aw url b had la methode
        //chaque espace f nom remplacih b -
        //bach n evitiw urls ikon mtchabhim
        //f lekher kanzid  time(), bach ikon unique
        $slug = Str::replaceArray(' ', ['-'], $request->title) .  '-'  . time();


        //nafs lblan pour le nom d'image
        $imageName = $request->title . '-'  . time()  . '.' .  $request->image->getClientOriginalExtension();

        //kan placiw l'image f dossier /public/img
        $request->image->move(public_path('img'), $imageName);

        //jib le chemin dyal image
        $path = '/img/' . $imageName;


        //creer lproduct
        Product::create(array_merge($request->all(), ['slug' => $slug, 'image' => $path]));

        //redirect la route 'GET /productmanager', m3a wahd lmessage temporaire smito 'success'
        return redirect()->route('productmanager.index')
            ->with('success', 'Product has been added successfully.');
    }


    //route GET /productmanager/{id}
    public function edit($id)
    {
        //jib l product li ID = $id
        //sinon firstOrFail = 404
        $product = Product::where('id', $id)->firstOrFail();

        //afficher lview li kayna fi /resources/views/productmanager/edit.blade.php 
        //osift lya m3aha les variables 'product'

        return view('productmanager.edit', compact('product'));
    }

    //route PUT /productmanager/{id}
    public function update(Request $request, $id)
    {
        //jib l product li ID = $id
        //sinon firstOrFail = 404
        $product = Product::where('id', $id)->firstOrFail();

        //validation des champs
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'price' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',

        ]);


        //9ad slug, aw url b had la methode
        //chaque espace f nom remplacih b -
        //bach n evitiw urls ikon mtchabhim
        //f lekher kanzid  time(), la
        $slug = Str::replaceArray(' ', ['-'], $request->title) .  '-'  . time();

        //nafs lblan pour le nom d'image
        $imageName = $request->title . '-'  . time()  . '.' . $request->image->getClientOriginalExtension();

        //kan placiw l'image f dossier /public/img
        $request->image->move(public_path('img'), $imageName);

        //jib le chemin dyal image
        $path = '/img/' . $imageName;

        //update lproduct
        $product->update(array_merge($request->all(), ['slug' => $slug, 'image' => $path]));

        //redirect la route 'GET /productmanager', m3a wahd lmessage temporaire smito 'success'
        return redirect()->route('productmanager.index')
            ->with('success', 'Product has been updated successfully.');
    }


    //route DELETE /productmanager/{id}
    public function destroy($id)
    {
        //jib l product li ID = $id
        //sinon firstOrFail = 404
        $product = Product::where('id', $id)->firstOrFail();

        //delete the product
        $product->delete();

        //redirect la route 'GET /productmanager', m3a wahd lmessage temporaire smito 'success'
        return redirect()->route('productmanager.index')
            ->with('success', 'Product has been deleted successfully.');
    }
}

resources/views/productmanager/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="float-left">
                <h2>Add a new product</h2>
            </div>
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('productmanager.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>There are some errors.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
        </div>
    @endif
    {{-- {{ dd(Auth::user()->id) }} --}}
    <form action="{{ route('productmanager.store') }}" method="POST" enctype="multipart/form-data">
        @csrf


        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title">
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" rows="3" name="description"></textarea>
        </div>

        <div class="form-group">
            <label for="price">Price</label>
            <input type="number" class="form-control" id="price" name="price">
        </div>
        <div class="form-group">
            <label for="price">Category</label>
            <select class="form-control" name="category_id">
                @foreach ($categories as $category)
                    <option value={{ $category->id }}>{{ $category->title }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <input type="file" class="form-control-file" id="image" name="image">
        </div>

        <button class="btn btn-dark" type="submit">Create Product</button>


    </form>
@endsection

resources/views/productmanager/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Edit a product</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-primary" href="{{ route('productmanager.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>There are some errors.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
</div>
@endif
<form action="{{ route('productmanager.update', $product->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control" id="title" name="title" value="{{$product->title}}">
    </div>

    <div class="form-group">
        <label for="description">Description</label>
        <textarea class="form-control" id="description" rows="3" name="description">{{$product->description}}</textarea>
    </div>

    <div class=" form-group">
        <label for="price">Price</label>
        <input type="number" class="form-control" id="price" name="price" value="{{$product->price}}">
    </div>

    <div class="form-group">
        <img src="{{$product->image}}" alt="" class="w-25 mb-5">
        <input type="file" class="form-control-file" id="image" name="image" value="{{$product->image}}">
    </div>

    <button class="btn btn-dark" type="submit">Update Product</button>


</form>
@endsection

resources/views/productmanager/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row mb-2">
    <div class="col-lg-12 margin-tb">
        <div class="float-right">
            <a class="btn btn-primary" href="{{ route('productmanager.create') }}">Create a new product</a>
        </div>
    </div>
</div>
@if ($products->isNotEmpty())
<table class="table table-striped table-bordered">
    <tr class="align-middle text-center">
        <th>Image</th>
        <th>Title</th>
        <th>Price</th>
        <th>Action</th>
    </tr>
    @foreach ($products as $product)
    <tr>
        <td class="align-middle text-center w-25"><img src="{{$product->image}}" class="w-25"></td>
        <td class="align-middle text-center ">{{ $product->title }}</td>
        <td class="align-middle text-center ">{{ $product->price }} DH</td>
        <td class="align-middle text-center w-50">
            <form action="{{ route('productmanager.destroy',$product->id) }}" method="POST">

                <div class="row">
                    <div class="col-lg-4">
                        <a class="btn btn-dark mb-1" href="{{ route('products.show',$product->slug) }}">Show</a>
                    </div>
                    <div class="col-lg-4">
                        <a class="btn btn-dark mb-1" href="{{ route('productmanager.edit',$product->id) }}">Edit</a>
                    </div>
                    <div class="col-lg-4">
                        <button type="submit" class="btn btn-danger m-0">Delete</button>
                    </div>
                </div>



                @csrf
                @method('DELETE')

            </form>
        </td>
    </tr>
    @endforeach
</table>

{!! $products->links() !!}
@else
<h1 class="text-centerh">No products</h1>
@endif

@endsection