routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Gloudemans\Shoppingcart\Facades\Cart;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});




Route::get('/', 'MainController@index')->name('index');
Route::resource('category', 'CategoryController');
Route::get('/price/{mix}/{max}', 'PriceController@show')->name('price.show');

Route::get('/products', 'ProductController@index')->name('products.index');
Route::get('/products/{id}', 'ProductController@show')->name('products.show');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/admin', 'AdminController@index')->name('admin.index');

    Route::resource('categorymanager', 'CategoryManagerController');
    Route::resource('productmanager', 'ProductManagerController');
    Route::resource('usermanager', 'UserManagerController');
    Route::resource('ordermanager', 'OrderManagerController');


    //Orders
    Route::resource('/orders', 'OrderController');

    Route::get('/thank-you', function () {
        return view('thank-you');
    })->name('thank-you');

    Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');
    Route::post('/checkout', 'CheckoutController@store')->name('checkout.store');
    //cart
    Route::get('/cart', 'CartController@index')->name('cart.index');
    Route::post('/cart', 'CartController@store')->name('cart.store');

    Route::post('/cart/empty', 'CartController@empty')->name('cart.empty');
    Route::delete('/cart/{id}', 'CartController@destroy')->name('cart.destroy');
    Route::put('/cart/{id}', 'CartController@update')->name('cart.update');


    //Profile
    Route::get('/profile', 'ProfileController@index')->name('profile.index');
    Route::get('/profile/{id}/edit', 'ProfileController@edit')->name('profile.edit');
    Route::put('/profile/{id}', 'ProfileController@update')->name('profile.update');
});

app/Http/Controllers/CategoryManagerController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;

class CategoryManagerController extends Controller
{
    //page admin
    //route GET /categorymanager
    public function index()
    {

        //selectioner tous les categories
        $categories = Category::all();
        //SELECT * FROM categories

        //afficher lview li kayna fi /resources/views/categorymanager/index.blade.php 
        //osift lya m3aha les variables 'categories'
        return view('categorymanager.index', compact('categories'));
    }



    //route GET /categorymanager/create
    public function create()
    {
        //afficher lview li kayna fi /resources/views/categorymanager/create.blade.php 
        return view('categorymanager.create');
    }



    //route POST /categorymanager
    public function store(Request $request)
    {

        //creer la category

        //inserer une categorie
        Category::create([
            'title' => $request->title,
            'slug' => Str::replaceArray(' ', ['-'], $request->title),
            'description' => $request->description,
        ]);
        /* 
        INSERT INTO categories (title, slug, description)
        VALUES (Category A, category-a, Category A Description)
        */

        //redirect la route 'GET /categorymanager', m3a wahd lmessage temporaire smito 'success'
        return redirect()->route('categorymanager.index')
            ->with('success', 'Category has been added successfully.');
    }



    //route GET /categorymanager/{id}
    public function edit($id)
    {
        //jib l category li ID = $id
        //sinon firstOrFail = 404
        $category = Category::where('id', $id)->firstOrFail();

        //afficher lview li kayna fi /resources/views/categorymanager/edit.blade.php 
        //osift lya m3aha les variables 'category'
        return view('categorymanager.edit', compact('category'));
    }

    //route PUT /productmanager/{id}
    public function update(Request $request, $id)
    {
        $category = Category::where('id', $id)->firstOrFail();

        //mise a jour d'une categorie
        $category->update(
            [
                'title' => $request->title,
                'slug' => Str::replaceArray(' ', ['-'], $request->title) .  '-'  . time(),
                'description' => $request->description,
            ]
        );
        /* 
        UPDATE categories
        SET
            title = "Category A",
            slug = "category-a",
            description = "Category A Description",
        WHERE id = 1
        */

        //redirect la route 'GET /categorymanager', m3a wahd lmessage temporaire smito 'success'
        return redirect()->route('categorymanager.index')
            ->with('success', 'Category has been updated successfully.');
    }

    //route DELETE /categorymanager/{id}
    public function destroy($id)
    {
        //jib l category li ID = $id
        //sinon firstOrFail = 404
        //supprimer une categorie
        Category::destroy($id);
        /* 
        DELETE FROM categories
        WHERE id = 1
        */
        //redirect la route 'GET /categorymanager', m3a wahd lmessage temporaire smito 'success'
        return redirect()->route('categorymanager.index')
            ->with('success', 'category has been deleted successfully.');
    }
}

resources/views/categorymanager/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Add a new category</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-primary" href="{{ route('categorymanager.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>There are some errors.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
</div>
@endif
<form action="{{ route('categorymanager.store') }}" method="POST" enctype="multipart/form-data">
    @csrf


    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control" id="title" name="title">
    </div>

    <div class="form-group">
        <label for="description">Description</label>
        <textarea class="form-control" id="description" rows="3" name="description"></textarea>
    </div>

    <button class="btn btn-dark" type="submit">Create Category</button>


</form>
@endsection

resources/views/categorymanager/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="float-left">
            <h2>Edit a category</h2>
        </div>
        <div class="float-right">
            <a class="btn btn-primary" href="{{ route('categorymanager.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>There are some errors.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
</div>
@endif
<form action="{{ route('categorymanager.update', $category->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control" id="title" name="title" value="{{$category->title}}">
    </div>

    <div class="form-group">
        <label for="description">Description</label>
        <textarea class="form-control" id="description" rows="3" name="description">{{$category->description}}</textarea>
    </div>

    <button class="btn btn-dark" type="submit">Update category</button>


</form>
@endsection

resources/views/categorymanager/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="row mb-2">
        <div class="col-lg-12 margin-tb">
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('categorymanager.create') }}">Create a new category</a>
            </div>
        </div>
    </div>
    @if ($categories->isNotEmpty())
        <table class="table table-striped table-bordered">
            <tr class="align-middle text-center">
                <th>Title</th>
                <th>Action</th>
            </tr>
            @foreach ($categories as $category)
                <tr>
                    <td class="align-middle text-center ">{{ $category->title }}</td>
                    <td class="align-middle text-center w-50">
                        <form action="{{ route('categorymanager.destroy', $category->id) }}" method="POST">

                            <div class="row">
                                <div class="col-lg-4">
                                    <a class="btn btn-dark mb-1"
                                        href="{{ route('categorymanager.edit', $category->id) }}">Edit</a>
                                </div>
                                <div class="col-lg-4">
                                    <button type="submit" class="btn btn-danger m-0">Delete</button>
                                </div>
                            </div>



                            @csrf
                            @method('DELETE')

                        </form>
                    </td>
                </tr>
            @endforeach
        </table>

        {!! $categories->links() !!}
    @else
        <h1 class="text-centerh">No categories</h1>
    @endif

@endsection