routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Gloudemans\Shoppingcart\Facades\Cart;
use App\Http\Controllers\CategoryController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});




Route::get('/', 'MainController@index')->name('index');
Route::resource('category', 'CategoryController');
Route::get('/price/{mix}/{max}', 'PriceController@show')->name('price.show');

Route::get('/products', 'ProductController@index')->name('products.index');
Route::get('/products/{id}', 'ProductController@show')->name('products.show');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/admin', 'AdminController@index')->name('admin.index');

    Route::resource('categorymanager', 'CategoryManagerController');
    Route::resource('productmanager', 'ProductManagerController');
    Route::resource('usermanager', 'UserManagerController');
    Route::resource('ordermanager', 'OrderManagerController');


    //Orders
    Route::resource('/orders', 'OrderController');

    Route::get('/thank-you', function () {
        return view('thank-you');
    })->name('thank-you');

    Route::get('/checkout', 'CheckoutController@index')->name('checkout.index');
    Route::post('/checkout', 'CheckoutController@store')->name('checkout.store');
    //cart
    Route::get('/cart', 'CartController@index')->name('cart.index');
    Route::post('/cart', 'CartController@store')->name('cart.store');

    Route::post('/cart/empty', 'CartController@empty')->name('cart.empty');
    Route::delete('/cart/{id}', 'CartController@destroy')->name('cart.destroy');
    Route::put('/cart/{id}', 'CartController@update')->name('cart.update');


    //Profile
    Route::get('/profile', 'ProfileController@index')->name('profile.index');
    Route::get('/profile/{id}/edit', 'ProfileController@edit')->name('profile.edit');
    Route::put('/profile/{id}', 'ProfileController@update')->name('profile.update');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $guarded = [];

    //chaque product momkin it ajouta lbzaf d les paniers
    public function carts()
    {
        return $this->belongsToMany('App\Cart');
    }

    //chaque product momkin ikon f bzaf d les orders
    public function orders()
    {
        return $this->belongsToMany('App\Order');
    }

    //chaque product kayntami l category whda
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    //route GET /products
    public function index()
    {
        //jib tous les products
        //pagination par 12
        $products = Product::paginate(12);

        //afficher lview li kayna fi /resources/views/products/index.blade.php 
        //osift lya m3aha les variables 'products'
        return view('products.index', compact('products'));
    }

    //route GET /products/{slug}
    public function show($slug)
    {
        //obtenier le produit avec slug = $slug
        //sinon firstOrFail = 404
        $product = Product::where('slug', $slug)->firstOrFail();

        //obtenir 4 produit qui sont similaires
        $products = Product::where('title', 'like', "%$product->title%")
            ->inRandomOrder()
            ->take(4)
            ->get();

        //afficher la page de produit avec les variables 'products', 'product'
        return view('products.show', compact(['products', 'product']));
    }
}

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-light">
            <li class="breadcrumb-item"><a href="/" class="text-dark">Home</a></li>
            <li class="breadcrumb-item active">

                @if (isset($title))
                    All Our {{ $title }}'s
                @else
                    All products
                @endif

                </a>
            </li>
        </ol>
    </nav>
    <div class="row mt-5">

        <div class="col-md-3">
            <h3 class="mb-5">Sort By</h3>
            <div><span class=" h5"><i class="far fa-list-alt"></i>&nbsp;Category</span>
                <ul class="cat-list">
                    <li><a href="{{ route('category.show', 'iphone') }}" class="text-dark">iPhone</a></li>
                    <li><a href="{{ route('category.show', 'ipad') }}" class="text-dark">iPad</a></li>
                    <li><a href="{{ route('category.show', 'macbook') }}" class="text-dark">Macbook</a></li>

                </ul>
            </div>
            <div><span class="h5"><i class="fas fa-dollar-sign"></i>&nbsp;Price<br></span>
                <ul class="cat-list">
                    <li><a href="{{ route('price.show', ['0', '1000']) }}" class="text-dark">0-1000</a></li>
                    <li><a href="{{ url('/price/2001/3000') }}" class="text-dark">2001-3000</a></li>
                    <li><a href="{{ route('price.show', ['1001', '2000']) }}" class="text-dark">1001-2000</a></li>
                    <li><a href="{{ route('price.show', ['2001', '3000']) }}" class="text-dark">2001-3000</a></li>
                    <li><a href="{{ route('price.show', ['3001', '4000']) }}" class="text-dark">3001-4000</a></li>
                    <li><a href="{{ route('price.show', ['4001', '5000']) }}" class="text-dark">4001-5000</a></li>
                    <li><a href="{{ route('price.show', ['5001', '6000']) }}" class="text-dark">5001-6000</a></li>
                    <li><a href="{{ route('price.show', ['6001', '7000']) }}" class="text-dark">6001-7000</a></li>
                    <li><a href="{{ route('price.show', ['7001', '8000']) }}" class="text-dark">7001-8000</a></li>
                    <li><a href="{{ route('price.show', ['8001', '9000']) }}" class="text-dark">8001-9000</a></li>
                    <li><a href="{{ route('price.show', ['9001', '10000']) }}" class="text-dark">9001-10000</a></li>


                </ul>
            </div>
        </div>
        <div class="col-md-9">


            <h3 class="mb-5">
                @if (isset($description))
                    {{ $description }}
                @endif
            </h3>

            <div>
                <div class="row mb-2">

                    @foreach ($products as $product)
                        <div class="col-12 col-sm-4 mb-4">
                            <a class="text-decoration-none text-dark" href="/products/{{ $product->slug }}">

                                <div class="card shadow-sm text-center"><img class="card-img-top w-100 d-block product-img"
                                        src="{{ $product->image }}">

                                    <div class="card-body d-flex justify-content-between align-items-center">
                                        <h4 class="card-title mb-0 text-capitalize">
                                            {{ Str::replaceArray('-', [' '], $product->title) }}
                                        </h4>

                                        <div><span class="badge badge-dark"><span
                                                    class="mr-1">{{ $product->price }}</span><span>DH</span></span>

                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>

                    @endforeach
                </div>

            </div>
        </div>
    </div>

    <div class="d-flex justify-content-center">
        {!! $products->links() !!}
    </div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-light ">
        <li class="breadcrumb-item "><a href="/" class="text-dark">Home</a></li>
        <li class="breadcrumb-item"><a href="{{route('products.index')}}" class="text-dark">Products</a></li>
        <li class="breadcrumb-item active text-capitalize " aria-current="page">
            {{ Str::replaceArray('-', [' '], $product->title) }}</li>
    </ol>
</nav>

<div class="row mt-5">
    <div class="col-12 col-md-6" id="product-col-1"><img class="w-75" src="{{$product->image}}"></div>

    <div class="col-12 col-md-6 d-flex flex-column justify-content-between" id="product-col-2">
        <div>
            <h2 id="product-title" class="text-capitalize">{{ Str::replaceArray('-', [' '], $product->title) }}</h2>



            <div id="product-price"><span class="badge badge-dark p-3"><span
                        class="mr-1">{{$product->price}}</span><span>DH</span></span>

            </div>
        </div>
        <p id="product-desc">{{$product->description}}<br><br><br></p>

        {{-- {{dd($product->id)}} --}}



        @if(Auth::user()!==null)
        <form
            action="{{ Auth::user()->role != "admin" ? route('cart.store') : route('productmanager.edit', $product->id)}}"
            method="{{ Auth::user()->role != "admin" ? 'POST' : 'GET'}}">
            @else
            <form action="{{route('cart.store')}}" method="POST">
                @endif

                @csrf
                <input type="hidden" name="id" id="id" value="{{$product->id}}">
                <input type="hidden" name="title" id="title" value="{{$product->title}}">
                <input type="hidden" name="price" id="price" value="{{$product->price}}">


                @if(Auth::user() == null or Auth::user()->role != "admin")
                <button class="btn btn-dark text-uppercase text-center d-lg-flex align-items-lg-start text-center"
                    data-bs-hover-animate="pulse" id="product-cto" type="submit">Add to Cart</button>
                @elseif(Auth::user()->role == "admin")
                <button class="btn btn-dark text-uppercase text-center d-lg-flex align-items-lg-start text-center"
                    data-bs-hover-animate="pulse" id="product-cto" type="submit">Edit Product</button>

                @endif
            </form>

    </div>
</div>
<h3 class="text-center my-5">You Might Also Like</h3>
<div class="row product-row">
    @foreach($products as $product)
    <div class="col-12 col-sm-6 col-md-3">
        <a class="text-decoration-none text-dark" href="{{$product->slug}}">

            <div class="card shadow-sm text-center"><img class="card-img-top w-100 d-block product-img"
                    src="{{$product->image}}">

                <div class="card-body d-flex justify-content-between align-items-center">
                    <h4 class="card-title mb-0 text-capitalize">{{ Str::replaceArray('-', [' '], $product->title) }}
                    </h4>
                    <div>
                        <span class="badge badge-dark">
                            {{$product->price}}
                            <span>DH</span>
                        </span>
                    </div>
                </div>
            </div>
        </a>
    </div>

    @endforeach

</div>
@endsection